module.exports = function(app){
    app.get('/pop',function(req,res){
        //Pop
        //category1
    });
    app.get('/hip-hop',function(req,res){
        //Hip-hop
        //category2
    });
    app.get('/old-school-hh',function(req,res){
        //Old School Hip Hop
        //category3
    });
    app.get('/trap',function(req,res){
        //Trap
        //category4
    });
    app.get('/electro',function(req,res){
        //Electro
        //category5
    });
    app.get('/rnb',function(req,res){
        //R&B
        //category6
    });
    app.get('/techno',function(req,res){
        //Techno
        //category7
    });
    app.get('/dubstep',function(req,res){
        //Dubstep
        //category8
    });
    app.get('/acapella',function(req,res){
        //Acapella
        //category9
    });
    app.get('/tropical',function(req,res){
        //Tropical
        //category10
    });
    app.get('/bass-house',function(req,res){
        //Bass House
        //category11
    });
    app.get('/dance',function(req,res){
        //Dance
        //category12
    });
    app.get('/instrumental',function(req,res){
        //Instrumental
        //category13
    });
    app.get('/jazz',function(req,res){
    //     Jazz
    //category14
    });
    app.get('/orchestral',function(req,res){
    //  Orchestral
    //category15
    });
    app.get('/disco',function(req,res){
        //Disco
        //category16
    });
    app.get('/heavy-metal',function(req,res){
        //Heavy Metal
        //category17
    });
    app.get('/classical',function(req,res){
        //Classical
        //category18
    });
    app.get('/salsa',function(req,res){
        //Salsa
        //category19
    });
    app.get('/romantic',function(req,res){
        //Romantic
        //category20
    });
    app.get('/funk',function(req,res){
        //Funk
        //category21
    });
    app.get('/reggae',function(req,res){
        //Reggae
        //category22
    });
    app.get('/house',function(req,res){
        //House
        //category23
    });
    app.get('/tango',function(req,res){
        //Tango
        //category24
    });
    app.get('/blues',function(req,res){
        //Blues
        //category25
    });
    app.get('/punkrock',function(req,res){
        //Punk Rock
        //category26
    });
    app.get('/country',function(req,res){
        //Country
        //category27
    });
    app.get('/alternative',function(req,res){
        //Alternative
        //category28
    });
    app.get('/gospel',function(req,res){
            //Gospel
            //category29
    });
    app.get('/indie',function(req,res){
            //Indie
            //category30
    });
    app.get('/rock',function(req,res){
        //Rock
        //category31
    });
    app.get('/deep-house',function(req,res){
        //Deep House
        //category32
    });
    app.get('/world-reggae',function(req,res){
        //World Reggae
        //category33
    });
    app.get('/trance',function(req,res){
        //Trance
        //category34
    });
    app.get('/trance',function(req,res){
        //Soul
        //category35
    });
    app.get('/punk-rock',function(req,res){
        //World Punk Rock
        //category36
    });
    app.get('/drum-bass',function(req,res){
        //Drum'n Bass
        //category37
    });
    app.get('/rythem',function(req,res){
        //Rythem
        //category38
    });
    app.get('/smooth-jazz',function(req,res){
        //Smooth Jazz
        //category39
    });
    app.get('/meditation',function(req,res){
        //Meditation
        //category40
    });
};

